language: c
install:
- git submodule update --init
- pip install PyYAML --target pyyaml --use-mirrors
env: PYTHONPATH=$TRAVIS_BUILD_DIR/pyyaml
compiler:
- gcc
- clang
script: cmake . && make && ctest -V
