#include <sys/queue.h>
#include <stdio.h>
#include <assert.h>

#include "genheader.h"
#include "yparser.h"
#include "codes.h"
#include "cutil.h"
#include "access.h"


struct scalar_type_s {
    char *tag;
    char *typ;
} scalar_types[] = {
    {"!Int", "long"},
    {"!Float", "double"},
    {"!File", "char*"},
    {"!Dir", "char*"},
    {"!String", "char*"},
    {"!Bool", "int"},
    {NULL, NULL}
    };


static int print_member(qu_context_t *ctx, qu_ast_node *node) {
    qu_nodedata *data = node->userdata;
    if(!data)
        return 0;
    if(data->kind == QU_MEMBER_SCALAR) {
        struct scalar_type_s *st = scalar_types;
        for(;st->tag;++st) {
            if(!strncmp((char *)node->tag->data, st->tag,
                        node->tag->bytelen)) {
                printf("%s %s;\n", st->typ, strrchr(data->expression, '.')+1);
                return 0;
            }
        }
        fprintf(stderr, "Wrong tag \"%.*s\"\n",
                node->tag->bytelen, node->tag->data);
        return -1;
    } else if(data->kind == QU_MEMBER_STRUCT) {
        printf("struct {\n");
        qu_ast_node *key;
        CIRCLEQ_FOREACH(key, &node->children, lst) {
            int rc = print_member(ctx, key->value);
            assert(rc >= 0);
        }
        printf("} %s;\n", strrchr(data->expression, '.')+1);
    }

    return 0;
}


int qu_output_header(qu_context_t *ctx) {
    printf("/* DO NOT EDIT THIS FILE! */\n");
    printf("/* This file is generated */\n");
    printf("#ifndef _H_%s\n", ctx->macroprefix);
    printf("#define _H_%s\n", ctx->macroprefix);
    printf("\n");
    printf("#include <quire.h>\n");
    printf("\n");

    // TODO describe array|mapping element structures

    printf("typedef struct %scli_s {\n", ctx->prefix);
    printf("char *cfg_filename;\n");
    printf("uint64_t cfg_flags;\n");
    printf("int cfg_mode;\n");
    qu_nodedata *data;
    TAILQ_FOREACH(data, &ctx->cli_options, cli_lst) {
        printf("unsigned %s_set:1;\n", data->cli_name);
    }
    TAILQ_FOREACH(data, &ctx->cli_options, cli_lst) {
        struct scalar_type_s *st = scalar_types;
        for(;st->tag;++st) {
            if(!strncmp((char *)data->node->tag->data, st->tag,
                        data->node->tag->bytelen)) {
                printf("%s %s;\n", st->typ, data->cli_name);
                if(qu_map_get(data->node, "command-line-incr")
                   || qu_map_get(data->node, "command-line-decr")) {
                    printf("%s %s_delta;\n", st->typ, data->cli_name);
                    printf("unsigned %s_delta_set;\n", data->cli_name);
                }
            }
        }
    }
    printf("} %scli_t;\n", ctx->prefix);
    printf("\n");

    printf("typedef struct %smain_s {\n", ctx->prefix);
    qu_ast_node *key;
    CIRCLEQ_FOREACH(key, &ctx->parsing.document->children, lst) {
        int rc = print_member(ctx, key->value);
        assert(rc >= 0);
    }
    printf("} %smain_t;\n", ctx->prefix);

    printf("\n");  //end of types

    printf("int %1$sload(%1$smain_t *cfg, int argc, char **argv);\n",
        ctx->prefix);
    printf("int %1$sprint(%1$smain_t *cfg, int flags, FILE *);\n",
        ctx->prefix);
    printf("int %1$sfree(%1$smain_t *cfg);\n", ctx->prefix);

    printf("\n");
    printf("#endif  // _H_%s\n", ctx->macroprefix);
    return 0;
}
